import random
import logging
from card import GenericCard

class TaroService:
    def fill_Cards(self):
        self.cards = list()
        self.cards.append(GenericCard('Туз Чаш', 'Нахождение в преддверии исполнения желаний, весть, которая принесет радость и счастье, мир и гармонию', 'D:\dev\Pictures\cups_ace.jpg'))
        self.cards.append(GenericCard('Король Чаш', 'Получение мудрого совета, утешения и поддержки', 'D:\dev\Pictures\cups_king.jpg'))
        self.cards.append(GenericCard('Дама Чаш', 'Присутствие достаточно яркой эмоциональной реакции, переживания', 'D:\dev\Pictures\cups_queen.jpg'))
        self.cards.append(GenericCard('Рыцарь Чаш', 'Послание истинной и взаимной любви', 'D:\dev\Pictures\cups_prince.jpg'))
        self.cards.append(GenericCard('Паж Чаш', 'Приятные переживания, свежие чувства, новые знакомства', 'D:\dev\Pictures\cups_page.jpg'))
        self.cards.append(GenericCard('Двойка Чаш', 'Гармоничные отношения между двумя людьми, их растущий интерес друг к другу', 'D:\dev\Pictures\cups_2.jpg'))
        self.cards.append(GenericCard('Тройка Чаш', 'Успех задуманного дела, восстановление добрых отношений', 'D:\dev\Pictures\cups_3.jpg'))
        self.cards.append(GenericCard('Четверка Чаш', 'Хандра, уныние, погруженность в прошлое и незамечание настоящего', 'D:\dev\Pictures\cups_4.jpg'))
        self.cards.append(GenericCard('Пятерка Чаш', 'Трудные отношения или неожиданные неприятности и помехи в делах, скорбь о потерянном', 'D:\dev\Pictures\cups_5.jpg'))
        self.cards.append(GenericCard('Шестерка Чаш', 'Преуспевание без усилий в гармоничной обстановке, проявление щедрости, великодушия и любви, радость жизни и внутренняя гармония', 'D:\dev\Pictures\cups_6.jpg'))
        self.cards.append(GenericCard('Семерка Чаш', 'Иллюзорность, нестабильности достижений, сбивание с толку', 'D:\dev\Pictures\cups_7.jpg'))
        self.cards.append(GenericCard('Восьмерка Чаш', 'Печальное прощание с прошлым, переходный период, когда меняются жизненные цели и приоритеты', 'D:\dev\Pictures\cups_8.jpg'))
        self.cards.append(GenericCard('Девятка Чаш', 'Глубокое удовлетворение, гармония, исполнение желаний, полное довольствие событиями и результатом действий', 'D:\dev\Pictures\cups_9.jpg'))
        self.cards.append(GenericCard('Десятка Чаш', 'Гармония в семейных отношениях, наполнение домашнего очага', 'D:\dev\Pictures\cups_10.jpg'))
        self.cards.append(GenericCard('Туз Мечей', 'Достаточное количество сил для энергичных начинаний, огромная решимость действовать, начало успешной борьбы, готовность к росту, отрыву от изначального существования', 'D:\dev\Pictures\swords_ace.jpg'))
        self.cards.append(GenericCard('Король Мечей', 'Вдохновленность какими-то новыми серьезными идеями и устремленность к новым целям', 'D:\dev\Pictures\swords_king.jpg'))
        self.cards.append(GenericCard('Дама Мечей', 'Некая личная потеря, печаль, утрата, лишения, огорчения', 'D:\dev\Pictures\swords_queen.jpg'))
        self.cards.append(GenericCard('Рыцарь Мечей', 'Стремительно развивающиеся стрессовые ситуации, превратности судьбы, попадание в центр каких-то перипетий', 'D:\dev\Pictures\swords_prince.jpg'))
        self.cards.append(GenericCard('Паж Мечей', 'Грядущие испытания и непредсказуемое коварство судьбы', 'D:\dev\Pictures\swords_page.jpg'))
        self.cards.append(GenericCard('Двойка Мечей', 'Гармония, твердость, сбалансированная сила, компенсирующие факторы, согласие, обдуманность решений, точность суждения, реальная оценка ситуации', 'D:\dev\Pictures\swords_2.jpg'))
        self.cards.append(GenericCard('Тройка Мечей', 'Выбор, сделанный вопреки чувству, отречение от чего-то дорогого', 'D:\dev\Pictures\swords_3.jpg'))
        self.cards.append(GenericCard('Четверка Мечей', 'Бессмысленность борьбы  в настоящий момент', 'D:\dev\Pictures\swords_4.jpg'))
        self.cards.append(GenericCard('Пятерка Мечей', 'Жизнь входит в стрессовую полосу, ситуацию, освободиться от которой удастся не сразу, возможно месть', 'D:\dev\Pictures\swords_5.jpg'))
        self.cards.append(GenericCard('Шестерка Мечей', 'Выход из сложной, запутанной или даже опасной ситуации, уход от проблем', 'D:\dev\Pictures\swords_6.jpg'))
        self.cards.append(GenericCard('Семерка Мечей', 'Попытка при помощи каких-то трюков и махинаций найти выход из сложной ситуации, избежать конфликта', 'D:\dev\Pictures\swords_7.jpg'))
        self.cards.append(GenericCard('Восьмерка Мечей', 'Попадание в очень затруднительное положение', 'D:\dev\Pictures\swords_8.jpg'))
        self.cards.append(GenericCard('Девятка Мечей', 'Неуправляемая волна тревоги, тоски, страха, вины, ужаса перед жизнью, которая вздымается в бессознательном', 'D:\dev\Pictures\swords_9.jpg'))
        self.cards.append(GenericCard('Десятка Мечей', 'Полный провал, боль, неудача, опустошение', 'D:\dev\Pictures\swords_10.jpg'))
        self.cards.append(GenericCard('Туз Пентаклей', 'Процветание, достаточность, доход, обилие ресурсов, прежде всего земных', 'D:\dev\Pictures\pentacles_ace.jpg'))
        self.cards.append(GenericCard('Король Пентаклей', 'Подъем в делах, успех в любом предприятии, стабильная карьера и хорошие перспективы, особенно в развитии долговременных проектов', 'D:\dev\Pictures\pentacles_king.jpg'))
        self.cards.append(GenericCard('Дама Пентаклей', 'Благоприятные события, соответствующие желаниям, безопасная и стабильная материальная реальность', 'D:\dev\Pictures\pentacles_queen.jpg'))
        self.cards.append(GenericCard('Рыцарь Пентаклей', 'Импульс ответственности, добросовестности, исполнительности и силы воли', 'D:\dev\Pictures\pentacles_prince.jpg'))
        self.cards.append(GenericCard('Паж Пентаклей', 'Хороший шанс начать новый проект касаемо учебы, работы и доходов', 'D:\dev\Pictures\pentacles_page.jpg'))
        self.cards.append(GenericCard('Двойка Пентаклей', 'Наличие равновесия в каком-то вопросе', 'D:\dev\Pictures\pentacles_2.jpg'))
        self.cards.append(GenericCard('Тройка Пентаклей', 'Идеи материализуются, задуманное воплощается в жизнь, мечты осуществляются, причем благодаря усилиям самого человека и оценке со стороны других людей', 'D:\dev\Pictures\pentacles_3.jpg'))
        self.cards.append(GenericCard('Четверка Пентаклей', 'Расчетливость и тщательное планирование, готовность действовать, чтобы достичь желаемой стабильности или сохранить существующий порядок', 'D:\dev\Pictures\pentacles_4.jpg'))
        self.cards.append(GenericCard('Пятерка Пентаклей', 'Хорошее время для любви, но плохое для денег', 'D:\dev\Pictures\pentacles_5.jpg'))
        self.cards.append(GenericCard('Шестерка Пентаклей', 'Ожидание награды, восстановленного благополучия, решения прежних проблем, получения желаемого, сбывшихся надежд, материальной выгоды', 'D:\dev\Pictures\pentacles_6.jpg'))
        self.cards.append(GenericCard('Семерка Пентаклей', 'Провал, несостоятельность, бесперспективные вложения, внушающее надежду протекание какого-то процесса, который пока не окончен и потребует дальнейших усилий', 'D:\dev\Pictures\pentacles_7.jpg'))
        self.cards.append(GenericCard('Восьмерка Пентаклей', 'Умелая, мастерская и очень тщательная работа, какое-то дело, предельная концентрация и полное погружение', 'D:\dev\Pictures\pentacles_8.jpg'))
        self.cards.append(GenericCard('Девятка Пентаклей', 'Осуществление и достижение цели, успех, всевозможное изобилие, награда за благоразумный выбор', 'D:\dev\Pictures\pentacles_9.jpg'))
        self.cards.append(GenericCard('Десятка Пентаклей', 'Период богатства, стабильности, полноты жизни и уверенности в завтрашнем дне', 'D:\dev\Pictures\pentacles_10.jpg'))
        self.cards.append(GenericCard('Туз Жезлов', 'Новые возможности и неожиданные события на подходе', 'D:\dev\Pictures\wands_ace.jpg'))
        self.cards.append(GenericCard('Король Жезлов', 'Перспективные деловые проекты, карьерный рост и возможность многого достичь на профессиональном поприще', 'D:\dev\Pictures\wands_king.jpg'))
        self.cards.append(GenericCard('Дама Жезлов', 'Достижение карьерного роста, делового успеха, популярности и известности', 'D:\dev\Pictures\wands_queen.jpg'))
        self.cards.append(GenericCard('Рыцарь Жезлов', 'Разлука, отъезд, уход, бегство, дезертирство, отсутствие какого-то человека, переселение, эмиграция, смена адреса', 'D:\dev\Pictures\wands_prince.jpg'))
        self.cards.append(GenericCard('Паж Жезлов', 'Путешественник, посланец, добрый друг, эмиссар, иностранец, долгожданное известие, гонец с вестями', 'D:\dev\Pictures\wands_page.jpg'))
        self.cards.append(GenericCard('Двойка Жезлов', 'Удача и могущество, но несчастье и крах', 'D:\dev\Pictures\wands_2.jpg'))
        self.cards.append(GenericCard('Тройка Жезлов', 'Рост, стабильность и успех', 'D:\dev\Pictures\wands_3.jpg'))
        self.cards.append(GenericCard('Четверка Жезлов', 'Благожелательность и процветание, заметный и заслуженный успех и признание, отличная обстановка, приход счастья', 'D:\dev\Pictures\wands_4.jpg'))
        self.cards.append(GenericCard('Пятерка Жезлов', 'Отстаивании собственных интересов среди таких же, конкуренция', 'D:\dev\Pictures\wands_5.jpg'))
        self.cards.append(GenericCard('Шестерка Жезлов', 'Благоприятный исход любого дела, его доведение до победного конца, триумф воли и мужества', 'D:\dev\Pictures\wands_6.jpg'))
        self.cards.append(GenericCard('Семерка Жезлов', 'Имеет место непростая ситуация, чье-то вмешательство в личные дела, кампания по противодействию, попытка лишить чего-либо или помешать чего-то добиться', 'D:\dev\Pictures\wands_7.jpg'))
        self.cards.append(GenericCard('Восьмерка Жезлов', 'Ожидаемые события начинают неудержимо разворачиваться, все пришло в движение, противодействия больше не существует и вскоре что-то произойдет', 'D:\dev\Pictures\wands_8.jpg'))
        self.cards.append(GenericCard('Девятка Жезлов', 'Обретение способности выдерживать любые испытания на прочность, достойно противостоять любым трудностям и вызовам реальности', 'D:\dev\Pictures\wands_9.jpg'))
        self.cards.append(GenericCard('Десятка Жезлов', 'Сила, воля и выносливость, которые нужны, чтобы справиться с затеянным когда-то делом', 'D:\dev\Pictures\wands_10.jpg'))
        self.cards.append(GenericCard('Колесница', 'Огромный скачок вперед, преодоление препятствий, уверенный прорыв', 'D:\dev\Pictures\chariot.jpg'))
        self.cards.append(GenericCard('Влюбленные', 'Выбор, испытание, внутриличностный конфликт', 'D:\dev\Pictures\lovers.jpg'))
        self.cards.append(GenericCard('Жрец', 'Вопросы этики, процесс обучения и участие в каких-то ритуалах и церемониях', 'D:\dev\Pictures\hierophant.jpg'))
        self.cards.append(GenericCard('Император', 'Стабильность, надежность, покровительство, помощь, содействие росту и реализация планов', 'D:\dev\Pictures\emperor.jpg'))
        self.cards.append(GenericCard('Императрица', 'Предвестие насыщенного времени, богатого несущими удовлетворение событиями', 'D:\dev\Pictures\empress.jpg'))
        self.cards.append(GenericCard('Жрица', 'Присутствие тайны, присутствие различного рода подсказок, указателей на жизненном пути', 'D:\dev\Pictures\priestess.jpg'))
        self.cards.append(GenericCard('Маг', 'Появление новых возможностей для решения старых проблем, достижения поставленных целей, ожидается скорое развитие событий', 'D:\dev\Pictures\magician.jpg'))
        self.cards.append(GenericCard('Справедливость', 'Личная ответственность и проявление в жизни кармического правосудия, необходимости отработать долги и уплатить по счетам', 'D:\dev\Pictures\justice.jpg'))
        self.cards.append(GenericCard('Отшельник', 'Cтремление замкнуться и потребность в самоанализе, обретение внутреннего мира и собственной правды, следование своим путем', 'D:\dev\Pictures\hermit.jpg'))
        self.cards.append(GenericCard('Колесо Фортуны', 'Будущее решается сейчас, но не по вашей воле', 'D:\dev\Pictures\wheel.jpg'))
        self.cards.append(GenericCard('Сила', 'Испытание на выносливость, необходимость в терпении и смелости', 'D:\dev\Pictures\strenght.jpg'))
        self.cards.append(GenericCard('Повешенный', 'Необходимость каких-то жертв и нового подхода, неприятности', 'D:\dev\Pictures\hangedman.jpg'))
        self.cards.append(GenericCard('Смерть', 'Переход, окончание, трансформация', 'D:\dev\Pictures\death.jpg'))
        self.cards.append(GenericCard('Умеренный', 'Смягчение разногласий и снижение напряженности, какое-то испытание', 'D:\dev\Pictures\emperance.jpg'))
        self.cards.append(GenericCard('Шут', 'Перекресток жизненных дорог, новый виток развития, чистая нерастраченная энергия', 'D:\dev\Pictures\ool.jpg'))
        self.cards.append(GenericCard('Дьявол', 'Страх, злоупотребление силой, потакание своей слабости', 'D:\dev\Pictures\devil.jpg'))
        self.cards.append(GenericCard('Башня', 'Кризис, взрыв или слом после предшествовавшего нагнетания', 'D:\dev\Pictures\ower.jpg'))
        self.cards.append(GenericCard('Звезда', 'Существование высшей путеводной силы, которой необходимо довериться', 'D:\dev\Pictures\star.jpg'))
        self.cards.append(GenericCard('Луна', 'Наличие в повседневной жизни неприятных эмоциональных проявлений', 'D:\dev\Pictures\moon.jpg'))
        self.cards.append(GenericCard('Солнце', 'Самый расцвет жизни, счастье бытия, ощутимый успех', 'D:\dev\Pictures\sun.jpg'))
        self.cards.append(GenericCard('Суд', 'Благополучное завершение какой-либо кризисной фазы, чудесное избавление от множества трудностей, перспектива одним махом избавиться от всего, что гнетет и давит', 'D:\dev\Pictures\judgement.jpg'))
        self.cards.append(GenericCard('Мир', 'Несомненный успех задуманного, исполнение всех желаний, счастливое завершение хода событий', 'D:\dev\Pictures\world.jpg'))

    def create_logger(self):
        self.logger = logging.getLogger("taro_service")
        self.logger.setLevel(logging.DEBUG)
        self.fh = logging.FileHandler("taro_service.log")
        self.logger.addHandler(self.fh)

    def __init__(self):
        self.create_logger()
        self.fill_Cards()
        self.logger.info("Successfully created taro service")

    def get_taro_cards(self):
        try:
            return(random.sample(self.cards, 3))
        except Exception as ex:
            self.logger.error(str(ex))
            self.logger.error('Unable to send cards!')
